#!/bin/bash

#Author: R. Lica, razvan.lica@cern.ch

if [ -z $1 ] 
  then
    echo "ERROR: Run number required as argument (eg: 00X)."
    exit 1
fi

FILE2="refRun_ClovE-beta-R$1.cmat";
    
       if [ -f $FILE2 ]; then
         echo Removing existing file: $FILE2
	 rm -f $FILE2
       fi


FILE1="refRun_ClovE-R$1.cmat";
    
       if [ -f $FILE1 ]; then
         echo Removing existing file: $FILE1
	 rm -f $FILE1
       fi

FILE3="Beta-RefRun-R$1.cmat";
    
       if [ -f $FILE3 ]; then
         echo Removing existing file: $FILE3
	 rm -f $FILE3
       fi



#Writing the sorting script used by GASPware

echo "format GASP

*** R. Lica
******************************************************
**** EXPERIMENT IS590 - June 2015 ********
******************************************************
*File generated by Sort-CloverBeta-run.sh



*-------------------------------------------------------------------------------------------
*                              Detector definitions
* C = Clover (1,2,3,4)
* L = LaBr (1,2)
* T = LaBr1_LaBr2 TAC
* B = Beta (Mid)     
* Coincidence time = HRT - 10 ns/chan 
* Time vs. Proton  = LRT - 10 ms/chan
* Time vs. Run Start = 100 s/chan

*-------------------------------------------------------------------------------------------
*                              Energy(0) HRT(1)    LRT(2)   TAC(3)  TAC_Start(3) TAC_Stop(4)  
*-------------------------------------------------------------------------------------------
header      F   1  8192 PLUS 1 8192
cdetector   C   4  SEG 4   3   8192      2048      8192
detector    L   2          4   8192      2048      8192	      8192
detector    T   1          5  16384      2048      8192             8192         8192
detector    B   1          3   8192      2048      8192
*-------------------------------------------------------------------------------------------


*---------------------------------------------------------
* Calibration
*---------------------------------------------------------

***ENERGY (1keV/chan)
recal        C0   Cal/ClovE_IS590_2  0.0	1.0  10   8192  0 16
*recal        L0   ./LaBrE-IS579    0.0	1.00  10   8192  0 2
**********************************************************
sort2d B0 B2 $FILE3 Res 8192 8192 Step 128 128 

addback C0

sort2d C2 C0 $FILE1 Res 8192 8192 Step 128 128
*sort3d Ci C2 C0 $FILE1 Res 128 8192 8192 Step 16 128 128

gate B0 100 8191 IN 1 1
gate B1 10 2000 IN 1 1
mean B1 F1
add  C1 F1 C1 Fact 1.00 -1.00 Off 1000
sort2d C2 C0 $FILE2 Res 8192 8192 Step 128 128
*sort3d Ci C2 C0 $FILE2 Res 128 8192 8192 Step 16 128 128" >script_R$1.setup

#Unpacking the raw data using Nutaq4IDS

n4i config_gasp_refRun <<echo
$1
$1
echo


gsort << echo
script_R$1.setup
256
256
256
D
Run$1
16
N
N
echo

n4i config_stat <<echo
$1
$1
echo

ls -lrth *$1.cmat

xtrackn 









